limit_error: true
limit_torques: true

filter.target_pose: 0.995
filter.q: 0.9
filter.dq: 0.0
max_delta_tau: 0.25

nullspace.stiffness: 20.0
nullspace.projector_type: dynamic
stop_commands: false

task.k_pos_x: 1500.0
task.k_pos_y: 1500.0
task.k_pos_z: 1500.0
task.k_rot_x: 1300.0
task.k_rot_y: 1300.0
task.k_rot_z: 1300.0

task.d_pos_x: 100.0
task.d_pos_y: 100.0
task.d_pos_z: 50.0
task.d_rot_x: 70.0
task.d_rot_y: 70.0
task.d_rot_z: 70.0

task.error_clip.rx: 0.5
task.error_clip.ry: 0.5
task.error_clip.rz: 0.5
task.error_clip.x: 0.1
task.error_clip.y: 0.1
task.error_clip.z: 0.1

use_coriolis_compensation: true
use_friction: false
use_gravity_compensation: false
use_local_jacobian: true
use_operational_space: true
use_sim_time: false
