limit_error: true
limit_torques: true

max_delta_tau: 0.5

filter.target_pose: 0.5
filter.q: 0.0
filter.dq: 0.0

nullspace.stiffness: 5.0
nullspace.projector_type: dynamic
stop_commands: false

task.k_pos_x: 900.0
task.k_pos_y: 700.0
task.k_pos_z: 800.0
task.k_rot_x: 50.0
task.k_rot_y: 50.0
task.k_rot_z: 50.0

task.d_pos_x: 50.0
task.d_pos_y: 120.0
task.d_pos_z: 50.0
task.d_rot_x: 10.0
task.d_rot_y: 10.0
task.d_rot_z: 10.0

task.error_clip.rx: 0.5
task.error_clip.ry: 0.5
task.error_clip.rz: 0.5
task.error_clip.x: 0.1
task.error_clip.y: 0.1
task.error_clip.z: 0.1

use_coriolis_compensation: true
use_friction: false
use_gravity_compensation: false
use_local_jacobian: true
use_operational_space: false
use_sim_time: false
